name: Main
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install
        run: yarn install
      - name: Unit Tests
        run: yarn test
      - name: Integration Tests
        run: | 
          yarn build
          yarn test:e2e
